from __future__ import annotations

import subprocess
import sys
from pathlib import Path

PYTHON = sys.executable
ROOT = Path(__file__).resolve().parents[1]


def run_command(args: list[str]) -> None:
    command = [PYTHON, "-m", "cli.main", *args]
    print("$", " ".join(command))
    subprocess.run(command, check=True, cwd=ROOT)


def main() -> None:
    demo_project = "project-demo"

    run_command(["project", "init", demo_project])
    run_command(
        [
            "issue",
            "create",
            "Demo issue from script",
            "--project",
            demo_project,
            "--description",
            "Generated by examples/demo_cli_flow.py",
            "--priority",
            "medium",
            "--tag",
            "demo",
        ]
    )
    run_command(["doc", "create", "readme", "--project", demo_project, "--title", "Demo Readme"])
    run_command(["issue", "list", "--project", demo_project])
    run_command(["issue", "done", "ISSUE-001", "--project", demo_project])
    run_command(["issue", "view", "ISSUE-001", "--project", demo_project, "--json"])

    print("Demo flow complete.")


if __name__ == "__main__":
    main()
