# install-hooks.ps1 — installs the pre-commit hook on Windows (PowerShell).
# Usage:  .\scripts\install-hooks.ps1
#         Run once from the repo root after cloning.

$ErrorActionPreference = "Stop"

$repoRoot = git rev-parse --show-toplevel
$hooksDir = Join-Path $repoRoot ".git\hooks"
$hookSource = Join-Path $repoRoot "scripts\hooks\pre-commit.ps1"
$hookDest = Join-Path $hooksDir "pre-commit"

if (-not (Test-Path $hookSource)) {
    Write-Error "Hook source not found at $hookSource"
    exit 1
}

# Write a thin shell wrapper that delegates to the PowerShell script so that
# Git (which always invokes hooks as a POSIX shell script) can find it.
$wrapperContent = @"
#!/usr/bin/env sh
# Auto-generated by scripts/install-hooks.ps1
powershell.exe -ExecutionPolicy Bypass -File "$(($hookSource -replace '\\', '/'))"
exit `$?
"@

Set-Content -Path $hookDest -Value $wrapperContent -Encoding ASCII

Write-Host "Installed pre-commit hook at $hookDest"
Write-Host "Run 'git commit --no-verify' to bypass the hook if needed."
